version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  continuous-integration:
  docker:
    - image: cimg/base:stable
  resource_class: medium
  steps:
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true

    - aws-ecr/build-and-push-image:
        create-repo: true
        dockerfile: Dockerfile
        path:
        platform: linux/amd64
        push-image: true
        region: '$(AWS_REGION)'
        repo: videosummarizer
        registry_id: AWS_ECR_REGISTRY_ID
        repo-scan-on-push: true
        tag: latest

  continuous-delivery:
    machine: true
    resource_class: vidya/video_sum
    steps:
      - aws-cli/setup

      - run:
          name: auth to aws ecr  
          command: aws ecr get-login-password --region us-east-1 | docker login --username --password-stdin <.........dkr.ecr.us-east-1.amazonaws.com>

      - run:
         name: pull image form private repo
         command: docker pull <.......dkr.ecr.us-east-1.amazonaws.com/videosummarizer.latest>     

      - run:
         name: run image
         command: docker run -d -p 5000:5000 <.......dkr.ecr.us-east-1.amazonaws.com/videosummarizer.latest> 
workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration 

